# Generated by Django 5.2.5 on 2025-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('passout_year', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('experience_details', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/candidates/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(max_length=15)),
                ('degree', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('passout_year', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('resume', models.FileField(upload_to='resumes/students/')),
            ],
        ),
    ]
